// Saturday, 11 Dec 2021  19:45:08
// has much of shift register stuff already.

const int latchPin = 2;  /* STCP */
const int clockPin = 3;  /* SHCP */
const int dataPin  = 4;  /* DS */

byte leds = 0;
byte uleds = 0;
byte pos = 15; // rightmost

void setup() {
  Serial1.begin(115200);
  Serial1.println("Begin.");
  pinMode(latchPin, OUTPUT);

#if 0
  pinMode(clockPin, OUTPUT);
  pinMode(dataPin,  OUTPUT);
#endif
}

void _digitSelect(void) {
    uleds = pos;
    shiftOut(dataPin, clockPin, MSBFIRST, uleds);
}

void updateShiftRegister(void) {
    digitalWrite(latchPin, LOW);
    _digitSelect(); // digit 0 1 2 or 3 using 'pos' as the index
    // BS init of 'leds':
    leds = 0; // NOT the program contents.
    uleds = leds;   // A-F 0-9 and a few other glyphs

    shiftOut(dataPin, clockPin, MSBFIRST, uleds); // paint the character's glyph!

    digitalWrite(latchPin, HIGH);
}

int count = -1;
char buffer[8];
int line_reset;

void loop() {
  count++;
  char * buf_ptr = & buffer[0];
  snprintf(buf_ptr, sizeof(buffer), " %02X %s", count, " ");
  Serial1.print(buffer);
  line_reset++;
  if (line_reset > 7) {
    line_reset = 0;
    // total BS
    // updateShiftRegister();
    Serial1.print('\n');
  }
  delay(444);
}


/**********   d o c u m e n t a t i o n   **********/

#if 0

 [ http://www.cplusplus.com/reference/cstdio/snprintf/]

int snprintf ( char * s, size_t n, const char * format, ... );

Write formatted output to sized buffer
Composes a string with the same text that
would be printed if format was used on
printf, but instead of being printed, the
content is stored as a C string in the
buffer pointed by s (taking n as the maximum
buffer capacity to fill).

#endif

#if 0
3V3 is the main 3.3V supply to RP2040 and
its I/O, generated by the on-board SMPS.

This pin can be used to power external circuitry
(maximum output current will depend on
RP2040 load and VSYS voltage,
it is recommended to keep the load on
this pin less than 300mA).
#endif
